### ISSUE TITLE
Example product > Collection example > Albums collection - Name of new Album can't be added

### ISSUE THREAD

**Issue by mrdavidlaing** [pivotal-cf-experimental/ops-manager-example#4]
When adding a new Album to the collection; one cannot ever change the name of the album.

This means that if you try to add multiple new albums; they are all named `Hello`

![image](https://user-images.githubusercontent.com/227505/90288095-0aacf800-de71-11ea-9f70-3a56f7140944.png)

**Comment by mingxiao** [comment]
We've updated the Album name to be configurable
