### ISSUE TITLE
Example product > Collection example > Album collection > Cannot enter Country of Origin field

### ISSUE THREAD

**Issue by mrdavidlaing** [pivotal-cf-experimental/ops-manager-example#5]
When configuring the Collection example > Album collection; you can never enter the Country of Origin or CF-Pop Service... because the tile is hardcoded as [`service_broker: false`](https://github.com/pivotal-cf-experimental/ops-manager-example/blob/master/example-product/metadata/example-product.yml.erb#L10)

![image](https://user-images.githubusercontent.com/227505/90288205-4b0c7600-de71-11ea-95a8-8a35c0f2b487.png)

**Comment by ctaymor** [comment]
I don't think this is a bug. As far as I know, service broker must be hardcoded either true or false, and is not configurable by the operator. We have a different service broker tile, the `example-broker-tile`. I suspect we leave these fields in to test that they are only configurable when the tile is a service broker, though I haven't checked the tests.

**Comment by ystros** [comment]
@mrdavidlaing As @ctaymor mentioned, this exists in the example product to exercise the behavior of embedded a service broker property within a non-service broker tile. Since these properties are marked as optional, their presence does not prevent the addition of records to the collection.
